### ISSUE TITLE
印刷物準備

### ISSUE THREAD

**Issue by springaki** [railsgirls-jp/kyoto#48]
印刷したらClose.
- [ ] ネームタグ
 - https://speakerdeck.com/railsgirls/nametags
 - 人数分+αになるような枚数。わりと縦幅がないので注意。各ページの一番下のネームタグが一番いいサイズになっているような...
 - 要裁断

- [ ] OSコマンドチートシート
  - https://github.com/railsgirls-jp/nagoya-team/blob/master/materials/Command_Cheatsheet.pdf
  - 15部くらい
  - どっちかしか使わないハズなので両面印刷でOK
　
　

gitコマンドのcheetsheetについては、
http://training.github.com/kit/downloads/ja/github-git-cheat-sheet.pdf
なのですが、印刷物をGithubさんから貰っているので、印刷不要。

**Comment by springaki** [comment]
@kensuke-m この内容でお願いできますでしょうか !!

**Comment by kensuke-m** [comment]
了解しました．

**Comment by springaki** [comment]
@kensuke-m ネームタグ可愛くて嬉しかったです。色々と印刷していただいて、ありがとうございました !!
